import Link from "next/link";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";

export const metadata = {
  title: "Akxai | Portfolio | Sanity",
  description: "Generated by create Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all the pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-4xl mx-auto pt-10 pb-20">
        <header className="flex items-center justify-between border-b-4 pb-4 mb-4">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Akxai
          </Link>

          <div className="flex items-center gap-5 text-sm capitalize text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline hover:scale-125 transition"
              >
                {page.slug}
              </Link>
            ))}
          </div>
        </header>

        <main className="py-10">{children}</main>
      </body>
    </html>
  );
}
